name: Self-hosted Bazel + GHS Pipeline
 
on:
  workflow_dispatch:   #  Run manually from GitHub UI
 
jobs:
  build:
    runs-on: self-hosted   # Use your Windows self-hosted runner
 
    steps:
      # Step 1: Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v4
 
      # Step 2: Add GHS compiler to PATH
      - name: Setup GHS compiler
        shell: cmd
        run: |
          echo Adding GHS compiler to PATH...
          set PATH=D:\ghs\comp_202014;%PATH%
          echo PATH is now: %PATH%
 
      # Step 3: Verify Bazel installation
      - name: Check Bazel version
        shell: cmd
        run: |
          bazel --version
 
      # Step 4: Run Bazel build with your GHS toolchain
      - name: Bazel build
        shell: cmd
        run: |
          echo Starting Bazel build with GHS toolchain...
          bazel build //:hello --crosstool_top=//toolchain:ghs_cc_toolchain
 
      # Step 5: Upload ELF as artifact (optional but useful)
      - name: Upload ELF artifact
        uses: actions/upload-artifact@v4
        with:
          name: ghs-build-output
          path: bazel-bin/**/*.elf