name: Build
on:
 push:
   branches: [ suji_bazeltest ]
 pull_request:
   branches: [ suji_bazeltest ]
jobs:
   # Stage 1: Checkout
  Checkout:
    name: Checkout Stage
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  compilerpathcheck:
    # Step 2: Add GHS compiler to PATH
    name: Set up GHS compiler path
    runs-on: windows-latest
    steps:
     - name: Set up GHS compiler path
       shell: cmd
       run: |
         echo Adding GHS compiler to PATH...
         set PATH=D:\ghs\comp_202014;%PATH% 
         echo PATH after: %PATH%
  compilerexecheck:
    # Stage 3: Verify Compiler
    name: Set up GHS compiler path
    runs-on: windows-latest
    steps:
      - name: Verify GHS compiler ccthumb.exe found or not
        shell: cmd
        run: |
          where ccthumb.exe
          if %errorlevel% neq 0 (
            echo GHS compiler not found!
            exit /b 1
          )
          ccthumb.exe -version
          ccthumb.exe -version || echo "GHS compiler not found!"
  build:
    # Step 3: Build with Bazel
    name: build Stage
    runs-on: windows-latest
    steps:
     # Step 3: Verify compiler is accessible
     #- name: Check GHS compiler
     #  shell: cmd
     #  run: |
     #    where ccthumb.exe
     #    ccthumb.exe -version || echo "GHS compiler not found!"
     # Step 4: Run Bazel build
     - name: Build with Bazel
       shell: cmd
       run: |
         echo Starting Bazel build...
         bazel build //:main_binary.elf